contracts/ibc-reflect-send/schema/execute_msg.json, contracts/ibc-reflect-send/schema/packet_msg.json, contracts/ibc-reflect/schema/packet_msg.json, contracts/reflect/schema/execute_msg.json, contracts/reflect/schema/response_for__custom_msg.json, packages/std/src/results/cosmos_msg.rs
Fix a typo in a document in code and execute cargo schema in contracts to reflect it to schemas.
=> chore: fix a typo in document and execute cargo schema in contracts

CHANGELOG.md, Cargo.lock, contracts/burner/Cargo.lock, contracts/crypto-verify/Cargo.lock, contracts/floaty/Cargo.lock, contracts/hackatom/Cargo.lock, contracts/ibc-reflect-send/Cargo.lock, contracts/ibc-reflect/Cargo.lock, contracts/queue/Cargo.lock, contracts/reflect/Cargo.lock, contracts/staking/Cargo.lock, contracts/voting-with-uuid/Cargo.lock, devtools/set_version.sh, packages/crypto/Cargo.toml, packages/derive/Cargo.toml, packages/schema/Cargo.toml, packages/std/Cargo.toml, packages/storage/Cargo.toml, packages/vm/Cargo.toml
fix devtools/set_version.sh and bump version.
=> release: Bump version to v0.16.3-0.5.0

CHANGELOG.md, Cargo.lock, contracts/burner/Cargo.lock, contracts/crypto-verify/Cargo.lock, contracts/floaty/Cargo.lock, contracts/hackatom/Cargo.lock, contracts/ibc-reflect-send/Cargo.lock, contracts/ibc-reflect/Cargo.lock, contracts/queue/Cargo.lock, contracts/reflect/Cargo.lock, contracts/staking/Cargo.lock, contracts/voting-with-uuid/Cargo.lock, packages/crypto/Cargo.toml, packages/derive/Cargo.toml, packages/schema/Cargo.toml, packages/std/Cargo.toml, packages/storage/Cargo.toml, packages/vm/Cargo.toml
=> build: Bump up the version 0.16.3-0.5.1

packages/derive/src/dynamic_link.rs
Closes #0
check extern abi for only allow the "C".
=> feat: check extern abi

contracts/query-queue/Cargo.toml
fix the author field of Cargo.toml of query-queue contract.
=> fix: fix author of query-queue contract

README.md
Since README.md was deleted in the previous merge, it is prepared again.
Closes #0
=> fix: re create README.md

.github/workflows/tests.yml, contracts/voting-with-uuid/.cargo/config, contracts/voting-with-uuid/src/coin_helpers.rs, contracts/voting-with-uuid/src/contract.rs, contracts/voting-with-uuid/src/tests.rs, contracts/voting-with-uuid/tests/integration.rs
#205 broke the ci (sorry for my carelessness). This PR fixes it.
=> ci: fix broken ci tests.yml

contracts/README.md
The path is wrong and it could not be compiled.
I fixed correct path.
=> fix: correct path

packages/std/src/global_api.rs, packages/std/src/lib.rs
=> fix: relax the limit of exporting targets of global env

packages/vm/src/backend.rs, packages/vm/src/dynamic_link.rs, packages/vm/src/testing/mock.rs
This PR is related to #223 
Modified error message when a callee function panicked(**It also needs to be modified on the wasmvm**)
A test in a mock environment in cosmwasm has also been added.
Please check it out.
=> feat: change error message

contracts/README.md, contracts/call-number/README.md, contracts/number/README.md
=> docs: fix README

.github/workflows/benchmarking.yml
fix .github/workflows/benchmarking.yml for dynamic_link branch following #209
=> ci: fix dynamic_link ci for benchmarking following #209

packages/vm/src/dynamic_link.rs
Closes #238 
Fixed an environment-dependent test that had been written.
=> fix: fix environment-dependent test

packages/vm/benches/main.rs
fix an error in bench (https://github.com/line/cosmwasm/actions/runs/3326486735/jobs/5500322669)
=> fix: fix vm bench

contracts/ibc-reflect-send/schema/execute_msg.json, contracts/ibc-reflect-send/schema/packet_msg.json, contracts/ibc-reflect/schema/packet_msg.json, contracts/reflect/schema/execute_msg.json, contracts/reflect/schema/response_for__custom_msg.json, packages/std/schema/cosmos_msg.json, packages/std/src/results/cosmos_msg.rs, packages/std/src/types.rs
Links that were not working were used, so it has been fixed.
I used `v0.46.0` as version.
=> docs: fix dead links

packages/vm/benches/main.rs
This PR is to avoid the error https://github.com/line/cosmwasm/actions/runs/3359799506/jobs/5568655612
=> ci: add setup process of dynamic link benchmarking to avoid runing out of gas

Cargo.lock, contracts/burner/Cargo.lock, contracts/call-number/Cargo.lock, contracts/call-number/Cargo.toml, contracts/crypto-verify/Cargo.lock, contracts/dynamic-callee-contract/Cargo.lock, contracts/dynamic-callee-contract/Cargo.toml, contracts/dynamic-caller-contract/Cargo.lock, contracts/dynamic-caller-contract/Cargo.toml, contracts/floaty/Cargo.lock, contracts/hackatom/Cargo.lock, contracts/ibc-reflect-send/Cargo.lock, contracts/ibc-reflect/Cargo.lock, contracts/number/Cargo.lock, contracts/query-queue/Cargo.lock, contracts/queue/Cargo.lock, contracts/reflect/Cargo.lock, contracts/staking/Cargo.lock, contracts/voting-with-uuid/Cargo.lock, packages/derive/src/lib.rs, packages/std/Cargo.toml
Closes #260 
Bump up `wasmer-types` version to **v2.2.1**
=> chore: bump wasmer-types version to v2.2.1

.github/workflows/tests.yml, contracts/events/schema/execute_msg.json, contracts/events/src/contract.rs
This PR fixes the events contract for dynamic link and adds some ci works.
=> fix: Fix events contract

contracts/dynamic-callee-contract/tests/integration.rs, contracts/number/tests/integration.rs, contracts/simple-callee/tests/integration.rs, packages/vm/src/backend.rs, packages/vm/src/environment.rs, packages/vm/src/instance.rs, packages/vm/src/testing/mock.rs
This PR removes unused dynamiclink features.
This is a part of #273
=> fix: Remove unused dynamiclink features

.github/workflows/release.yml
CI's release workflow fails now. This is because used rust-optimizer's version is old.
This PR updates the rust-optimizer used in release CI.
Closes #292
=> ci: update rust-optimizer version used in release ci

.github/workflows/release.yml
Before this commit, WASM was checked with vm/example/check_contracts.* in release CI.
This scripts are deleted and moved to package/check in latest version, so this commit change to use package/check.
Closes #297
=> ci: renew how to check the WASM in release

packages/vm/src/compatibility.rs
=> feat: check property function for dynamic linked callee contract

contracts/dynamic-callee-contract/src/contract.rs, contracts/dynamic-callee-contract/tests/integration.rs, contracts/dynamic-caller-contract/src/contract.rs, contracts/dynamic-caller-contract/tests/integration.rs, packages/std/src/errors/hash_calculation_error.rs, packages/std/src/errors/recover_pubkey_error.rs, packages/std/src/errors/std_error.rs, packages/std/src/errors/verification_error.rs
=> feat: StdResult (de)serializer

Cargo.lock, contracts/burner/Cargo.lock, contracts/call-number/Cargo.lock, contracts/crypto-verify/Cargo.lock, contracts/cyberpunk/Cargo.lock, contracts/dynamic-callee-contract/Cargo.lock, contracts/dynamic-caller-contract/Cargo.lock, contracts/events/Cargo.lock, contracts/floaty/Cargo.lock, contracts/hackatom/Cargo.lock, contracts/ibc-reflect-send/Cargo.lock, contracts/ibc-reflect/Cargo.lock, contracts/intermediate-number/Cargo.lock, contracts/number/Cargo.lock, contracts/query-queue/Cargo.lock, contracts/queue/Cargo.lock, contracts/reflect/Cargo.lock, contracts/simple-callee/Cargo.lock, contracts/staking/Cargo.lock, contracts/voting-with-uuid/Cargo.lock, packages/check/Cargo.toml, packages/crypto/Cargo.toml, packages/derive/Cargo.toml, packages/schema-derive/Cargo.toml, packages/schema/Cargo.toml, packages/std/Cargo.toml, packages/storage/Cargo.toml, packages/vm/Cargo.toml
set the version 1.1.9+0.7.0-dynamiclink2
This will be tagged after merged
=> build: Set version 1.1.9+0.7.0-dynamiclink2

contracts/call-number/src/contract.rs, contracts/call-number/src/error.rs
Fix error messages to appropriate ones.
Closes #319
=> fix: corrected to appropriate error message

contracts/README.md
Added `query_queue` docker command since there is no command of `query_queue` in `README`
=> docs: added query_queue docker command

README.md
This pr fixed typo error in README
=> chore: fix typo error

Cargo.lock, contracts/burner/Cargo.lock, contracts/crypto-verify/Cargo.lock, contracts/cyberpunk/Cargo.lock, contracts/floaty/Cargo.lock, contracts/hackatom/Cargo.lock, contracts/ibc-reflect-send/Cargo.lock, contracts/ibc-reflect/Cargo.lock, contracts/query-queue/Cargo.lock, contracts/queue/Cargo.lock, contracts/reflect/Cargo.lock, contracts/staking/Cargo.lock, contracts/voting-with-uuid/Cargo.lock, packages/check/Cargo.toml, packages/crypto/Cargo.toml, packages/derive/Cargo.toml, packages/schema-derive/Cargo.toml, packages/schema/Cargo.toml, packages/std/Cargo.toml, packages/storage/Cargo.toml, packages/vm/Cargo.toml
Set version to v1.1.9+0.8.0 because the cargo patch did not work well with the current v1.1.9-0.7.0
Tag after merge.
=> build: set version to 1.1.9+0.8.0

Cargo.lock, contracts/burner/Cargo.lock, contracts/crypto-verify/Cargo.lock, contracts/cyberpunk/Cargo.lock, contracts/floaty/Cargo.lock, contracts/hackatom/Cargo.lock, contracts/ibc-reflect-send/Cargo.lock, contracts/ibc-reflect/Cargo.lock, contracts/query-queue/Cargo.lock, contracts/queue/Cargo.lock, contracts/reflect/Cargo.lock, contracts/staking/Cargo.lock, contracts/voting-with-uuid/Cargo.lock, devtools/get_version.sh, packages/check/Cargo.toml, packages/crypto/Cargo.toml, packages/derive/Cargo.toml, packages/schema-derive/Cargo.toml, packages/schema/Cargo.toml, packages/std/Cargo.toml, packages/storage/Cargo.toml, packages/vm/Cargo.toml
Set version to `v1.1.9+0.8.1` and fix `get_version.sh` so that release github actions work properly.
Enabled release github actions to work properly with "+" instead of "-".
Tag after merge.
=> build: set version to 1.1.9+0.8.1 and fix get_version.sh

CONTRIBUTING.md
Added the description of versioning rule.
=> docs: add the description of versioning rule

.github/CODEOWNERS
=> refactor: update codeowners
