Finschia/cosmwasm

packages/std/src/lib.rs

In `StdError` like `OverflowError`, if the struct is positioned as a field, the struct type must also be exposed as `pub`.

fix: export DivideByZeroError to pub

---

packages/vm/src/testing/contract.rs
packages/vm/src/testing/mod.rs
packages/vm/src/testing/result.rs

This is caused by omitted exports in #86.
Closes #146.

fix: export vm::testing::contract::Contract

---

.github/workflows/release.yml
CHANGELOG.md

github action's release.yml fails because the used rust version is old.
https://github.com/line/cosmwasm/runs/5390425201?check_suite_focus=true
This PR updates the version.

fix: update rust version in release.yml

---

.github/workflows/release.yml
CHANGELOG.md

Excluding floaty from release checking. It fixes a missing in #160.

fix: exclude floaty from release checking

---

.github/workflows/release.yml
Cargo.lock
contracts/burner/Cargo.lock
contracts/crypto-verify/Cargo.lock
contracts/floaty/Cargo.lock
contracts/hackatom/Cargo.lock
contracts/ibc-reflect-send/Cargo.lock
contracts/ibc-reflect/Cargo.lock
contracts/queue/Cargo.lock
contracts/reflect/Cargo.lock
contracts/staking/Cargo.lock
contracts/voting-with-uuid/Cargo.lock
packages/vm/Cargo.toml

Closes #0
The wasmer version in the `cargo.lock` was changed to 2.1.1 by cargo update in previous PRs.
This causes the dependent library hashbrown to not build on rust 1.54.0.
In the process below, `wasmer` pointed to **2.0.0** in the `cargo.toml`, but the version was probably changed in the `cargo.lock` by cargo update.(change up twice, **2.1.0**, **2.1.1**)
https://github.com/line/cosmwasm/pull/160/files#r818241050
https://github.com/line/cosmwasm/commit/646b24e944d110362be11510009355fe75ddc59c#r67844444
Upstream cosmwasm 0.16.3 normally points to wasmer 2.0.0.
https://github.com/CosmWasm/cosmwasm/blob/22cfefab6217664e1e1d4baea2d1b6a48e6a4d62/Cargo.lock#L1706
- [] I have updated the documentation accordingly.

fix: downgrade wasmer version 2.0.0

---

.github/workflows/release.yml
CHANGELOG.md

release CD was failed.
it missed the copying with cargo.lock.
https://github.com/line/cosmwasm/runs/5401728405?check_suite_focus=true

fix: copy with cargo.lock

---

.github/workflows/release.yml

actions' release is now triggered also when PR is closed without merging.
This PR changes the trigger "PR closed" with "commits is added to the main branch".
Closes #171
tested in https://github.com/loloicci/cosmwasm-citest/pulls?q=is%3Apr+is%3Aclosed and https://github.com/loloicci/cosmwasm-citest/actions/workflows/release.yml .

fix: fix release.yml to trigger release only when PR is merged

---

.chglog/CHANGELOG.tpl.md
devtools/update_changelog.sh

This PR modifies chaglog template to
- filter commits that are not generated with "squash and merge" merging
- correct generating URLs for PR from `https://.../issues/XXX` to `https://.../pull/XXX`  in the suffix of PRs' title
And, modify to print a note to devtools/update_changelog.sh
Closes #164

fix: modify the chglog template to filter commits and correct PRs' URL

---

contracts/dynamic-callee-contract/src/contract.rs
contracts/dynamic-callee-contract/tests/integration.rs
contracts/dynamic-caller-contract/src/contract.rs
contracts/dynamic-caller-contract/tests/integration.rs
packages/std/src/global_api.rs
packages/std/src/lib.rs
packages/vm/src/calls.rs
packages/vm/src/compatibility.rs
packages/vm/src/environment.rs
packages/vm/src/ibc_calls.rs
packages/vm/src/imports.rs
packages/vm/src/instance.rs

Closes https://github.com/line/wasmvm/pull/61 https://github.com/line/lbm-sdk/pull/500
Adds a global API instead of the env that was passed as a parameter.
A contract can obtain information by calling the global API.

feat: add global api for to get env,deps in dynamic call

---

packages/vm/src/testing/contract.rs
packages/vm/src/testing/storage.rs

This PR simplifies `vm::testing::Contract` and makes it not take too much ownership of `Backend`.
This enables to specify the used querier and APIs in each generating instance from `Contract`. For example, using https://github.com/line/cosmwasm/pull/180 's `update_wasm` after constructing a contract needs this PR.

feat: simplify vm::testing::Contract

---

packages/vm/src/testing/contract.rs

Add memory_limit arg to some of Contract's functions. It limits memory when compiling WASM code.

feat: add memory_limit arg to some Contract's functions

---

contracts/dynamic-callee-contract/src/contract.rs
contracts/dynamic-callee-contract/tests/integration.rs
contracts/dynamic-caller-contract/schema/execute_msg.json
contracts/dynamic-caller-contract/src/contract.rs
contracts/dynamic-caller-contract/src/msg.rs
packages/vm/src/dynamic_link.rs
packages/vm/src/environment.rs
packages/vm/src/errors/vm_error.rs

Closes #155 https://github.com/line/wasmvm/pull/62
- add dynamic callstack for prevent the re-entrancy attack
- add max call depth limitation
about integration test,
cannot make the test logic with multiple contracts in the cosmwasm repo.
So I tested manually via `try_reentrancy` msg of `dynamic_caller_contract`.
Reentry is well blocked like this(A->B->A):
> {"height":"7","txhash":"066247EDDA6EB99AD88027D3B4B22A67434EBDC65CC87D7BB00E156A1D5865B9","codespace":"wasm","code":5,"data":"","raw_log":"failed to execute message; message index: 0: Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: func_info:{module_name:dynamic_callee_contract, name:stub_reentrancy, signature:[I32] -\u003e []}, error:Unknown error during call into backend: Some(\"Error executing Wasm: …

feat: add dynamic callstack for prevent the re-entrancy attack

---

packages/vm/src/backend.rs
packages/vm/src/dynamic_link.rs
packages/vm/src/testing/mock.rs
packages/vm/src/testing/mod.rs

Closes : #186 
- add unit test for dynamic link trampoline
- remove available gas parameter by contract_call
it's a refactoring for wasmvm side(https://github.com/line/wasmvm/pull/63).
It is appropriate to merge into separate PRs, but it is included in this PR because of too complex of changing the cosmwasm rev in wasmvm each time it is merged.

test: add unit test for dynamic link trampoline

---

packages/derive/src/callable_point.rs
packages/derive/src/dynamic_link.rs

Closes #186 
- add unit tests for #[dynamic_link] and #[callable_point]
Due to the limitations of proc macro test implementation,
test logic cannot be added where attribute and proc-macro-error are used.

test: add unit tests for #[dynamic_link] and #[callable_point]

---

contracts/query-queue/src/contract.rs

Before this PR, `query-queue`s entry point does not be exposed by `entry_points`. It causes an error while checking this contract.

fix: make query-queue's entry points using entry_points

---

.github/workflows/tests.yml
contracts/query-queue/src/contract.rs
contracts/query-queue/tests/integration.rs

feat: add integration tests for query-queue

---

.github/workflows/release.yml

Fix the bug that github release action is not working in new comwasm 1.0.0 version. 
This change is to change the versions of `rust-optimizer` and `rust` to the correction version.

ci: fix github release action bug

---

contracts/query-queue/Cargo.lock
contracts/query-queue/Cargo.toml
contracts/query-queue/schema/query_msg.json
contracts/query-queue/schema/raw_response.json
contracts/query-queue/src/contract.rs
contracts/query-queue/src/msg.rs
contracts/query-queue/tests/integration.rs

- update gas_limit to follow vm v1.0.0
- update how to query raw to follow queue v1.0.0
- change the result format of raw_query
This fixes #202

fix: update query-queue to version 1.0.0

---

.github/workflows/tests.yml
contracts/README.md

add voting_with_uuid contract to contract/README.md and tests in actions

fix: add voting_with_uuid to README and tests in actions

---

.github/workflows/tests.yml

Now, the key of action caches for contracts uses `cacheFiles('Cargo.lock')`. The `Cargo.toml` excludes `contracts/*`, so this key does not work well. This PR fix this to use `contracts/[contract-name]/Cargo.lock`.

fix: fix keys of action caches for contracts

---

contracts/README.md
contracts/dynamic-callee-contract/src/contract.rs
contracts/dynamic-callee-contract/src/msg.rs
contracts/dynamic-callee-contract/tests/integration.rs
contracts/dynamic-caller-contract/src/contract.rs
contracts/dynamic-caller-contract/src/msg.rs
contracts/dynamic-caller-contract/tests/integration.rs
packages/derive/src/callable_point.rs
packages/derive/src/dynamic_link.rs
packages/derive/src/lib.rs
packages/derive/src/utils.rs

feat: enable dynamic callee returns tuple typed value

---

packages/vm/src/errors/vm_error.rs

fix the error message for ReEntrancyError
Closes #193

fix: fix a error message for re-entrancy

---

.github/workflows/release.yml

Without this PR, if the release action does not create a new tag, the action ends with failure even if nothing fails. This PR fixes it and makes release actions end with success.
https://github.com/loloicci/auto-tag-test is an example of how it works.

fix: release action ends with success even if it does not renew tag

---

.github/workflows/benchmarking.yml

Fix broken workflow for benchmarking.
The cause of the error is the lack of dependent tests of `package_vm` and `crypt packages`. This PR adds them.
Closes #208

ci: fix broken workflow for benchmarking

---

packages/std/src/lib.rs

This PR limits exporting `GlobalEnv` only to wasm32 target.
Without this, the following error is caused during wasmvm's test for alpine linux.
```
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: api/libwasmvm_static.a(cosmwasm_std-bab964781d528372.cosmwasm_std.c8z0klf1-cgu.10.rcgu.o): in function `cosmwasm_std::global_api::GlobalApi::env':
cosmwasm_std.c8z0klf1-cgu.10:(.text._ZN12cosmwasm_std10global_api9GlobalApi3env17h764e247a0bf6c1faE+0x13): undefined reference to `global_env'
collect2: error: ld returned 1 exit status
make[1]: *** [release-build-alpine] Error 2
make: *** [release-build] Error 2
```

fix: limit exporting GlobalEnv only to wasm32 target

---

contracts/dynamic-callee-contract/src/contract.rs
contracts/dynamic-caller-contract/schema/query_msg.json
contracts/dynamic-caller-contract/src/contract.rs
contracts/dynamic-caller-contract/src/msg.rs
contracts/dynamic-caller-contract/tests/integration.rs
packages/derive/src/contract.rs
packages/derive/src/dynamic_link.rs
packages/derive/src/lib.rs
packages/derive/src/utils.rs
packages/derive/tests/test.rs
packages/std/src/lib.rs
packages/std/src/traits.rs
packages/vm/src/dynamic_link.rs

This PR changes how to specify the callee contract address in the caller contract.
For this purpose, it contains
- Define the `Contract` trait that represents the callee contract
- Implement a derive macro for `Contract`
- Modify the VM code to change from where the contract address is fetched
- Modify the `dynamic_link` macro
What is changed about the usage of the `#[dynamic_link]` macro is described in #207.
Closes #207

feat: improve how to specify the callee contract address

---

.github/workflows/benchmarking.yml
packages/vm/Cargo.toml
packages/vm/benches/main.rs
packages/vm/src/dynamic_link.rs
packages/vm/src/lib.rs
packages/vm/src/testing/environment.rs
packages/vm/src/testing/mock.rs

Add some benchmarks to estimate dynamic link gas cost.
- benchmarking `native_dynamic_link_trampoline`: used to estimate the gas cost to call for a dynamic linked function. calling a dynamic linked function takes this time and time to execute `contract_call`.
- benchmarking `read/write_region`: used to estimate the gas cost for copy values between two contract instances. This copy is executed in `contract_call`.

perf: Add benchmarks for estimate dynamic link gas cost

---

contracts/call-number/tests/integration.rs
contracts/dynamic-callee-contract/tests/integration.rs
contracts/dynamic-caller-contract/tests/integration.rs
contracts/number/tests/integration.rs
packages/derive/src/callable_point.rs
packages/derive/src/dynamic_link.rs

This PR renames generated function from `dynamic_link` and `callable_point` macro. This avoids the name conflict with other user-defined functions. See https://github.com/line/cosmwasm/issues/225 for detail.
Closes #225
Caller contracts and callee contracts need to use the same version of macros (before/after this PR).

fix: rename generated functions from dynamic_link and callable_point macro

---

.github/workflows/tests.yml

part of #228 (also push a PR to main)

ci: add tests for package derive

---

.github/workflows/tests.yml

ci: add ci tests for package derive

---

contracts/dynamic-caller-contract/src/contract.rs
packages/derive/src/dynamic_link.rs
packages/derive/src/lib.rs

This PR enables to make user-defined mock for impl generated by `dynamic_link` macro.
For detail see #227 and added tests in dynamic-caller-contract.
Before 7b1e6dea47b05b1d15fad0bb40de87f572b71d34 is the same as #226 (Review in progress).
Closes #227

feat: make available user defined mock for dynamic link

---

contracts/dynamic-callee-contract/src/contract.rs
contracts/dynamic-caller-contract/src/contract.rs
contracts/number/src/contract.rs
packages/derive/src/callable_point.rs
packages/derive/src/lib.rs
packages/std/src/exports.rs
packages/std/src/global_api.rs
packages/std/src/lib.rs

This PR changes the `callable_point` macro and makes callable point functions take `deps` typed `Deps` or `DepsMut` as the first arg.
For example,
before this PR:
```
#[callable_point]
fn add(by: i32) {
GlobalApi::with_deps_mut(|deps| handle_add(deps, by)).unwrap();
}
```
after this PR:
```
#[callable_point]
fn add(deps: DepsMut, by: i32) {
handle_add(deps, by).unwrap()
}
```
And, this PR removes GlobalApi's function to get deps.
Part of #213

feat: make callable point takes deps as the first arg

---

packages/vm/src/dynamic_link.rs
packages/vm/src/errors/communication_error.rs

This PR limits the max length of used by arg/return value's region with the dynamic link.
closes #190

feat: limit max regions' length used by calling dynamic link function

---

contracts/call-number/tests/integration.rs
contracts/dynamic-caller-contract/tests/integration.rs
packages/derive/src/dynamic_link.rs
packages/vm/src/compatibility.rs
packages/vm/src/dynamic_link.rs

Before this PR, importing modules like WASI API cannot be detected in the dynamic_link branch. This is because all importing is treated as dynamic link functions' import. We want to detect imports other than dynamic link functions and issue an error.
This PR changes the rule of the dynamic linked function's module name and forces them to start with "dynamiclinked_". 
solves #243 
These tests are done in https://github.com/line/lbm-sdk/pull/760 depending https://github.com/line/wasmvm/pull/78

feat: force the dynamic linked functions' module name to start with "dynamiclinked_"

---

packages/vm/src/backend.rs
packages/vm/src/errors/vm_error.rs
packages/vm/src/imports.rs

This PR related to https://github.com/line/cosmwasm/pull/244, https://github.com/line/wasmvm/pull/75
Reverted type of msg.
When applied, [test](https://github.com/line/wasmvm/actions/runs/3368121665/jobs/5586303360) will also be modified.
See: https://github.com/line/cosmwasm/commit/f3b919b31d72094e9e309be700e85fd602c5faa6

fix: revert type of Unknown msg

---

packages/vm/src/dynamic_link.rs

I fixed `max_address_length` and used `MAX_ADDRESS_LENGTH` on interface validation.
This PR is related to https://github.com/line/lbm-sdk/actions/runs/3618215697/jobs/6097827653.

fix: max address_length on interface validation

---

contracts/events/Cargo.toml
contracts/events/src/contract.rs
contracts/events/src/msg.rs

This PR improves the events contract to be useable as a dynamic linked contract. This contract is used by tests implemented in wasmvm's PR.
This was a part of https://github.com/line/cosmwasm/pull/269.

feat: improve events contract to be usable via dynamic link

---

packages/vm/src/environment.rs
packages/vm/src/instance.rs

This is a part of #273.
This PR implements `set_dynamic_callstack` and `call_function` to `Instance`.
And, this PR adds todo comments to some functions will be removed after solving #273

feat: implement set_dynamic_callstack and call_function to Instance

---

.github/workflows/tests.yml
contracts/call-number/src/contract.rs
contracts/dynamic-caller-contract/tests/integration.rs
contracts/events/schema/execute_msg.json
contracts/intermediate-number/src/contract.rs
contracts/simple-callee/src/contract.rs
contracts/simple-callee/tests/integration.rs
contracts/voting-with-uuid/src/contract.rs

Closes #284 
This PR adds clippy tests for contracts to ci and fixes contracts according to them.

ci: add lack clippy tests for some contracts and fix contracts according to them

---

packages/vm/src/testing/mock.rs
packages/vm/src/testing/mod.rs

`INSTANCE_CACHE` is a thread-local variable used in some tests for old dynamic link way.
https://github.com/Finschia/cosmwasm/blob/9161e25b9fa7f99bffde55af9601d2c0610347f1/packages/vm/src/testing/mock.rs#L43-L48
But, it is not used after #273. So This should be removed.
Closes #295

refactor: remove unused INSTNACE_CACHE

---

contracts/dynamic-callee-contract/src/contract.rs
contracts/dynamic-callee-contract/tests/integration.rs
contracts/dynamic-caller-contract/schema/execute_msg.json
contracts/dynamic-caller-contract/src/contract.rs
contracts/dynamic-caller-contract/src/msg.rs
contracts/dynamic-caller-contract/tests/integration.rs
packages/std/src/imports.rs
packages/std/src/testing/mock.rs
packages/std/src/traits.rs
packages/vm/src/compatibility.rs
packages/vm/src/imports.rs
packages/vm/src/instance.rs

This PR adds a way to get the caller address from dynamic link callee contracts.
And, this PR updates some sample contracts to test getting the caller address from the callee. The callee can call the same code's contract as a new callee. (only `get_caller_addr`)

feat: add get_caller_addr to deps.api

---

contracts/call-number/Cargo.toml
contracts/dynamic-callee-contract/Cargo.lock
contracts/dynamic-callee-contract/Cargo.toml
contracts/dynamic-caller-contract/Cargo.lock
contracts/dynamic-caller-contract/Cargo.toml
contracts/dynamic-caller-contract/src/contract.rs
contracts/events/Cargo.toml
contracts/intermediate-number/Cargo.toml
contracts/number/Cargo.lock
contracts/number/Cargo.toml
contracts/simple-callee/Cargo.lock
contracts/simple-callee/Cargo.toml
contracts/voting-with-uuid/Cargo.toml
packages/derive/src/lib.rs

https://github.com/Finschia/cosmwasm/blob/eda535b09ef7501752d633eb32eebc46cb1c9b92/packages/derive/src/lib.rs#L99-L101 is outdated and this is not needed in contracts using `#[callable_points]`
This PR
- deletes this comment
- removes not needed serde_json dependency from contracts
- formats a little in some Cargo.toml files
Closes #311

fix: delete outdated serde json

---

contracts/dynamic-caller-contract/src/contract.rs

chore: Added description about mock for callee

---

Cargo.lock
contracts/burner/Cargo.lock
contracts/call-number/Cargo.lock
contracts/crypto-verify/Cargo.lock
contracts/cyberpunk/Cargo.lock
contracts/dynamic-callee-contract/Cargo.lock
contracts/dynamic-caller-contract/Cargo.lock
contracts/events/Cargo.lock
contracts/floaty/Cargo.lock
contracts/hackatom/Cargo.lock
contracts/ibc-reflect-send/Cargo.lock
contracts/ibc-reflect/Cargo.lock
contracts/intermediate-number/Cargo.lock
contracts/number/Cargo.lock
contracts/query-queue/Cargo.lock
contracts/queue/Cargo.lock
contracts/reflect/Cargo.lock
contracts/simple-callee/Cargo.lock
contracts/staking/Cargo.lock
contracts/voting-with-uuid/Cargo.lock
packages/vm/Cargo.toml

This PR enables the VM to use WASM extension operators. 
This is a part of https://github.com/CosmWasm/cosmwasm/pull/1743.

feat: allow WASM extension operators

---

contracts/call-number/src/contract.rs

This PR has following changes.
- write explanatory comments on test functions in the sample contract
Closes #317

chore: write explanatory comments on test functions in the sample contract

---

Cargo.lock
contracts/burner/Cargo.lock
contracts/crypto-verify/Cargo.lock
contracts/cyberpunk/Cargo.lock
contracts/floaty/Cargo.lock
contracts/hackatom/Cargo.lock
contracts/ibc-reflect-send/Cargo.lock
contracts/ibc-reflect/Cargo.lock
contracts/query-queue/Cargo.lock
contracts/queue/Cargo.lock
contracts/reflect/Cargo.lock
contracts/staking/Cargo.lock
contracts/virus/Cargo.lock
contracts/voting-with-uuid/Cargo.lock
packages/crypto/Cargo.toml
packages/crypto/src/secp256k1.rs

fix https://github.com/CosmWasm/cosmwasm/issues/2010

fix: Bump k256 to ^0.13.3 (cherry-picking 9a6b365c352283119d78ed9f5ad715533fe8c3ae

---

packages/vm/src/cache.rs
packages/vm/src/compatibility.rs
packages/vm/src/modules/file_system_cache.rs
packages/vm/src/parsed_wasm.rs

This PR is related to https://github.com/Finschia/cosmwasm/pull/331, https://github.com/Finschia/cosmwasm/pull/336
Adopted Cosmwasm/cosmwasm [v1.5.1](https://github.com/CosmWasm/cosmwasm/tree/v1.5.1) to Finschia/cosmwasm.
This changes the base version of Finschia/cosmwasm from v1.1.9 to v1.5.1.
The test involving cosmwasm, wasmvm, and wasmd has not been done yet, so we will first merge into feat/bump_1.5.1. Once the test with all components working together is successful, will merge into main.
https://github.com/Finschia/cosmwasm/commit/602dab3bb11ae9cd47f3ba76aa1d52e6785906ea applied Cosmwasm/cosmwasm v1.5.1 to Finschia/cosmwasm feat/bump1.5.0 branch.

feat: bump up cosmwasm from v1.1.9 to v1.5.1
